import Head from "next/head";
import Image from "next/image";

import Banner from "../components/banner";
import Card from "../components/card";
import fetchCoffeeStores from "../lib/coffee-stores";
import useTrackLocation from "../hooks/use-track-location";

import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export async function getStaticProps(context) {
  const coffeeStores = await fetchCoffeeStores();
  return {
    props: {
      coffeeStores,
    }, // will be passed to the page component as props
  };
}
export default function Home(props) {
  const { handleTrackLocation, latLong, locationErrorMsg, isFindingLocation } =
    useTrackLocation();
  const [coffeeStores, setCoffeeStores] = useState();
  const [heading, setHeading] = useState("Istanbul Coffee Stores");
  const [coffeeStoresError, setCoffeeStoresError] = useState(null);
  useEffect(() => {
    if (latLong) {
      try {
        const fetchData = async () => {
          const fetchedCoffeeStore = await fetchCoffeeStores(latLong, 30);
          console.log({ fetchedCoffeeStore });
          setHeading("Stores near me");
          setCoffeeStores(fetchedCoffeeStore);
        };
        fetchData();
      } catch (error) {
        setCoffeeStoresError(error.message);
      }
    }
  }, [latLong]);
  const handleOnBannerButtonClick = () => {
    handleTrackLocation();
  };
  useEffect(() => setCoffeeStores(props.coffeeStores), []);

  useEffect(() => console.log({ coffeeStores }), [coffeeStores]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? "Locating..." : "View stores nearby"}
          handleOnClick={handleOnBannerButtonClick}
        />
        {locationErrorMsg && <p>Something went wrong... {locationErrorMsg}</p>}
        {coffeeStoresError && (
          <p>Something went wrong... {coffeeStoresError}</p>
        )}

        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="hero image"
            width={700}
            height={400}
          />
        </div>
        <div className={styles.sectionWrapper}>
          {coffeeStores?.length > 0 ? (
            <>
              <h2 className={styles.heading2}>{heading}</h2>
              <div className={styles.cardLayout}>
                {coffeeStores.map((coffeeStore) => (
                  <Card
                    key={coffeeStore.id}
                    imgUrl={
                      coffeeStore?.imgUrl ||
                      "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    }
                    name={coffeeStore.name}
                    id={coffeeStore.id}
                    className={styles.card}
                  />
                ))}
              </div>
            </>
          ) : (
            <div>No data fiound</div>
          )}
        </div>
      </main>
    </div>
  );
}
